In [1]:
import pretty_midi
import numpy as np
import librosa

In [3]:
sr = 100
pm = pretty_midi.PrettyMIDI('test.mid')
pr = pm.get_piano_roll(fs=sr, times=None)

In [4]:
print(pr)
print(pr.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(128, 1920)


In [7]:
print(pr.T[400])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 96.  0.  0. 96.
  0.  0.  0.  0.  0.  0.  0.  0. 96.  0.  0.  0.  0.  0.  0.  0.  0. 96.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]


In [5]:
pAvg = [np.mean(note) for note in pr]
print(pr[45][::10])
print(len(pr[45])/sr)
print(pm.get_end_time())

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 96. 96. 96. 96. 96. 96.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
19.2
19.2


In [11]:
ground_truth = []
fileOut = ''
for tTick, notes in enumerate(pr.T):
    time = str(tTick / 100.0)
    chord = [note for note, vel in enumerate(notes) if vel > 0]
    chordFreq = [str(librosa.core.midi_to_hz(note)) for note in chord]
    written = "{0}	{1}".format(time, '	'.join(chordFreq))
    fileOut += written + '\n'
#     print(time)
#     print(chord)
#     print(chordFreq)
#     print(written)
#     print()

print(fileOut)
        

0.0	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.01	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.02	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.03	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.04	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.05	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.06	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.07	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.08	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.09	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.1	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.11	130.8127826502993	329.6275569128699	391.99543598174927	523.2511306011972
0.12	130.8127826502993	329.6275569128699	391.99543598174927	523.25

In [13]:
def get_ground_truth(file_in, file_out): 
    sr = 100
    pm = pretty_midi.PrettyMIDI(file_in)
    pr = pm.get_piano_roll(fs=sr, times=None)
    ground_truth = []
    string_out = ''
    for tTick, notes in enumerate(pr.T):
        time = str(tTick / 100.0)
        chord = [note for note, vel in enumerate(notes) if vel > 0]
        chord_Freq = [str(librosa.core.midi_to_hz(note)) for note in chord]
        written = "{0}	{1}".format(time, '	'.join(chord_Freq))
        string_out += written + '\n'
    f = open(file_out, 'w+') 
    f.write(string_out) 
    f.close()
    
#     return string_out




In [15]:
get_ground_truth('test.mid', 'test.txt')